; Auto-generated. Do not edit!


(cl:in-package pr_msgs-msg)


;//! \htmlinclude herbFeedback.msg.html

(cl:defclass <herbFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform "")
   (progress
    :reader progress
    :initarg :progress
    :type cl:float
    :initform 0.0))
)

(cl:defclass herbFeedback (<herbFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <herbFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'herbFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_msgs-msg:<herbFeedback> is deprecated: use pr_msgs-msg:herbFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <herbFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr_msgs-msg:status-val is deprecated.  Use pr_msgs-msg:status instead.")
  (status m))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <herbFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr_msgs-msg:progress-val is deprecated.  Use pr_msgs-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <herbFeedback>) ostream)
  "Serializes a message object of type '<herbFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <herbFeedback>) istream)
  "Deserializes a message object of type '<herbFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<herbFeedback>)))
  "Returns string type for a message object of type '<herbFeedback>"
  "pr_msgs/herbFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'herbFeedback)))
  "Returns string type for a message object of type 'herbFeedback"
  "pr_msgs/herbFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<herbFeedback>)))
  "Returns md5sum for a message object of type '<herbFeedback>"
  "ce404b6cabcba81b67a4c8bac81c05d3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'herbFeedback)))
  "Returns md5sum for a message object of type 'herbFeedback"
  "ce404b6cabcba81b67a4c8bac81c05d3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<herbFeedback>)))
  "Returns full string definition for message of type '<herbFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%~%string status~%float32 progress~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'herbFeedback)))
  "Returns full string definition for message of type 'herbFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback message~%~%string status~%float32 progress~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <herbFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <herbFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'herbFeedback
    (cl:cons ':status (status msg))
    (cl:cons ':progress (progress msg))
))
