; Auto-generated. Do not edit!


(cl:in-package pr_msgs-msg)


;//! \htmlinclude herbResult.msg.html

(cl:defclass <herbResult> (roslisp-msg-protocol:ros-message)
  ((info
    :reader info
    :initarg :info
    :type cl:string
    :initform ""))
)

(cl:defclass herbResult (<herbResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <herbResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'herbResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_msgs-msg:<herbResult> is deprecated: use pr_msgs-msg:herbResult instead.")))

(cl:ensure-generic-function 'info-val :lambda-list '(m))
(cl:defmethod info-val ((m <herbResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pr_msgs-msg:info-val is deprecated.  Use pr_msgs-msg:info instead.")
  (info m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <herbResult>) ostream)
  "Serializes a message object of type '<herbResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'info))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'info))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <herbResult>) istream)
  "Deserializes a message object of type '<herbResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'info) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'info) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<herbResult>)))
  "Returns string type for a message object of type '<herbResult>"
  "pr_msgs/herbResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'herbResult)))
  "Returns string type for a message object of type 'herbResult"
  "pr_msgs/herbResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<herbResult>)))
  "Returns md5sum for a message object of type '<herbResult>"
  "c10fc26d5cca9a4b9114f5fc5dea9570")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'herbResult)))
  "Returns md5sum for a message object of type 'herbResult"
  "c10fc26d5cca9a4b9114f5fc5dea9570")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<herbResult>)))
  "Returns full string definition for message of type '<herbResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result message~%~%string info~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'herbResult)))
  "Returns full string definition for message of type 'herbResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result message~%~%string info~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <herbResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'info))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <herbResult>))
  "Converts a ROS message object to a list"
  (cl:list 'herbResult
    (cl:cons ':info (info msg))
))
