/* Auto-generated by genmsg_cpp for file /home/wu/ros_f_ws/sandbox/pr_msgs/msg/herbResult.msg */
#ifndef PR_MSGS_MESSAGE_HERBRESULT_H
#define PR_MSGS_MESSAGE_HERBRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace pr_msgs
{
template <class ContainerAllocator>
struct herbResult_ {
  typedef herbResult_<ContainerAllocator> Type;

  herbResult_()
  : info()
  {
  }

  herbResult_(const ContainerAllocator& _alloc)
  : info(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  info;


  typedef boost::shared_ptr< ::pr_msgs::herbResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::herbResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct herbResult
typedef  ::pr_msgs::herbResult_<std::allocator<void> > herbResult;

typedef boost::shared_ptr< ::pr_msgs::herbResult> herbResultPtr;
typedef boost::shared_ptr< ::pr_msgs::herbResult const> herbResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr_msgs::herbResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr_msgs::herbResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr_msgs::herbResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr_msgs::herbResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::herbResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const  ::pr_msgs::herbResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc10fc26d5cca9a4bULL;
  static const uint64_t static_value2 = 0x9114f5fc5dea9570ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::herbResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr_msgs/herbResult";
  }

  static const char* value(const  ::pr_msgs::herbResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::herbResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result message\n\
\n\
string info\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::pr_msgs::herbResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr_msgs::herbResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.info);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct herbResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_msgs::herbResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr_msgs::herbResult_<ContainerAllocator> & v) 
  {
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR_MSGS_MESSAGE_HERBRESULT_H

